# Generated by Django 5.1.4 on 2025-05-01 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('imgPath', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=100)),
                ('mpaa_type', models.CharField(max_length=10)),
                ('mpaa_label', models.TextField()),
                ('userRating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
        ),
    ]
